help: Makefile
	@sed -n 's/^## //p' $<

## npm-install-functions	-> Added dependencies in case that the functions need, add manually the command and Makefile 
functions-with-dependencies:
	cd src/handlers/automatic-clock-outs ; pwd ; $(MAKE) install

