# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: nodejs-functions

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: azure
  region: West US 2
  runtime: nodejs12
  # os: linux  # linux is the only operating system available for python
  prefix: "time-tracker"  # prefix of generated resource name
  environment:
    ENDPOINT: 'https://time-tracker-db.documents.azure.com:443/'
    KEY: '6lyRD8ma0VQjcMbeSMFOTDGwNDptcEGfngp3c9DStNAMCNh2MRbkNWmRinoNvuB6aH51EMEkgeP5WfW3VZiV9g=='
    CLIENT_ID: '5f930d3d-5f0d-43ed-8ba8-923b64341744'
    AUTHORITY: 'https://login.microsoftonline.com/cc925a5d-9644-4a4f-8d99-0bee49aadd05'
    CLIENT_SECRET: 'yFo=l7IS/5K7-J=49IYgw1?LU80U?U0d'
    SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'


custom:
  globalSchedule: cron(0 0 * * *)


plugins:
  - serverless-azure-functions
package:
  # include:
  #   - include-me.js
  #   - include-me-dir/**
  exclude:
    # - exclude-me.js
    # - exclude-me-dir/**
    - local.settings.json
    - .vscode/**

functions:
  automatic-clock-outs:
    prefix: automatic-clock-outs
    handler: src/handlers/automatic-clock-outs/index.js
    events:
      - timer: ${self:custom.globalSchedule}
