name: CD process to deploy to AzureFuncions

on:
  # Trigger the workflow on pull request but only for the master branch
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          npm i -g azure-functions-core-tools@core --unsafe-perm true
          cd AutomaticClockOuts
          npm install
          cd ../
          az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }}
          func settings add FUNCTIONS_WORKER_RUNTIME node
          func azure functionapp publish time-tracker-azure-functions --node
