name: CD process to deploy to AzureFuncions

on:
  # Trigger the workflow on pull request but only for the master branch
  pull_request:
    types: [closed]
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: AutomaticClockOuts    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'run npm'
        run: |
          npm install
          npm run build --if-present
      - uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
