name: CD process to deploy to AzureFuncions

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - pipe

env:
  AZURE_FUNCTIONAPP_NAME: 'time-tracker-azure-functions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'AutomaticClockOuts'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'run npm'
        run: |
          ls
#      - name: 'Run Azure Functions Action'
#        uses: Azure/functions-action@v1
#        id: fa
#        with:
#          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
