name: CD process to deploy to AzureFuncions

on:
  # Trigger the workflow on pull request but only for the master branch
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SOPS
        run: |
          sudo apt-get install wget
          wget https://github.com/mozilla/sops/releases/download/v3.7.0/sops_3.7.0_amd64.deb
          sudo dpkg -i sops_3.7.0_amd64.deb

      - name: Decrypt Secrets
        run: make sops-decrypt-nodejs

